# default config
server:
  port: 8081

my:
  name: "엄태권"
  age: 29
  api:
    country: "서울"
    marriage: false

spring:
  output:
    ansi:
      enabled: always

#logging:
#  file:
#    name: study.log
#  level:
#    root: warn
#    org.springframework.web: DEBUG
---

spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: test

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod