# default config
server:
  port: 8081

my:
  name: "엄태권"
  age: 29
  api:
    country: "서울"
    marriage: false

spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: test

---
spring:
  profiles:
    active: dev
server:
  port: ${random.int[8000, 9000]}

---
spring:
  profiles:
    active: prod

server:
  port: 5000